Implement multi export to png pictures
ostis-dev/kbe pull request #430
Opened 2020-12-02 08:52 UTC by Zioba

2020-12-02 15:06 UTC, ValikVityaz reviewed
Some simplifications

2020-12-02 15:06 UTC, ValikVityaz commented on sources/plugins/scg/scgwindow.cpp
> +    SCgExportImage exportImage;
```suggestion
{
    SCgExportImage exportImage;
```

2020-12-02 15:06 UTC, ValikVityaz commented on sources/plugins/scg/scgwindow.cpp
> +        fileName.append(QString::QString::number(index));
```suggestion
        fileName.append(QString::number(index));
```

2020-12-02 15:06 UTC, ValikVityaz commented on sources/plugins/scg/scgwindow.cpp
> +        fileName.append(sl[sl.size()-1]);
```suggestion
        fileName.append(sl.last());
```

2020-12-02 15:06 UTC, ValikVityaz commented on sources/plugins/scg/scgwindow.cpp
> +                fileName = fileName.left(fileName.size() - info.suffix().size()) + "png";
```suggestion
                filename = info.dir().dirName() + "/" + info.completeBaseName() + ".png";
```
This is probably more clear.

2020-12-02 15:06 UTC, ValikVityaz commented on sources/plugins/scg/scgwindow.cpp
> +    if (fileName.length() > 0)
```suggestion
    if (!fileName.isEmpty())
```
For more clarity & to conform with lines 468, 481.

2020-12-05 21:31 UTC, deniskoronchik commented
Fix comment in style like it was before

2020-12-05 21:42 UTC, deniskoronchik requested changes
Some improvements

2020-12-05 21:42 UTC, deniskoronchik commented on sources/kbe/interfaces/editorinterface.h
> +    virtual void exportToPng(int index) = 0;
Why we need that in an editor interface? For example why it should be implemented for any text editor?

2020-12-05 21:42 UTC, deniskoronchik commented on sources/kbe/main.cpp
> +    QApplication::setAttribute(Qt::AA_Use96Dpi);
Add comment with link, that describes this solution for HDPI?

2020-12-05 21:42 UTC, deniskoronchik commented on sources/plugins/scg/scgwindow.cpp
> +    QDir().mkdir(fileName);
```suggestion
    const QString kSubfolder("massExport");
    QDir dir(QCoreApplication::applicationDirPath());
    dir.mkpath(kSubfolder);   // also need to check if returns true. Some OS will have no permissions to create directory
    dir.cd(kSubfolder);
    
    QString fileName = dir.filePath(QString::number(index));
```

2020-12-07 20:57 UTC, deniskoronchik commented
Let do not use apply proposals button on github. It generate commit for each change. 
Also please fixup commits `Update sources/plugins/scg/scgwindow.cpp` into one. And change commit message to `Review fixes`

2020-12-20 21:38 UTC, deniskoronchik requested changes
Don't use concat operations for path. Let use already implemented cross-platform classes like `QDir`

2021-01-10 13:12 UTC, Zioba commented
Removed mass export feature from this PR
Renamed PR

2021-01-12 00:38 UTC, ValikVityaz approved these changes

2021-01-12 10:00 UTC, Zioba commented
https://github.com/ostis-dev/kbe/pull/430#discussion_r536896560
https://www.charlesodale.com/setting-qt-to-ignore-windows-dpi-text-size-personalization/

2021-01-12 10:01 UTC, Zioba commented on sources/kbe/interfaces/editorinterface.h
> +    virtual void exportToPng(int index) = 0;
We have no any text editors anymore.
As I know, there are no any plans to add any others editors in the future.

2021-01-12 10:01 UTC, Zioba commented on sources/kbe/main.cpp
> +    QApplication::setAttribute(Qt::AA_Use96Dpi);
https://www.charlesodale.com/setting-qt-to-ignore-windows-dpi-text-size-personalization/

2021-01-18 16:30 UTC, deniskoronchik commented on sources/kbe/main.cpp
> +    QApplication::setAttribute(Qt::AA_Use96Dpi);
I mean add comment into code

2021-01-18 16:31 UTC, deniskoronchik requested changes
Small changes

2021-01-18 20:58 UTC, KovalM approved these changes

2021-01-19 11:38 UTC, Zioba commented on sources/kbe/main.cpp
> +    QApplication::setAttribute(Qt::AA_Use96Dpi);
done

2021-01-19 13:35 UTC, deniskoronchik commented on sources/kbe/main.cpp
> +    //prevention of text scaling https://www.charlesodale.com/setting-qt-to-ignore-windows-dpi-text-size-personalization/
```suggestion
    // Disable text scaling https://www.charlesodale.com/setting-qt-to-ignore-windows-dpi-text-size-personalization/

```

2021-02-20 11:52 UTC, deniskoronchik commented on sources/kbe/main.cpp
> +    //Disable text scaling https://www.charlesodale.com/setting-qt-to-ignore-windows-dpi-text-size-personalization/
```suggestion
    // Disable text scaling https://www.charlesodale.com/setting-qt-to-ignore-windows-dpi-text-size-personalization/

```

2021-02-20 11:52 UTC, deniskoronchik requested changes
Simple fix

2021-03-16 13:43 UTC, deniskoronchik approved these changes

2021-03-16 14:26 UTC, merged