WIP: Implement new scg format
ostis-dev/kbe pull request #431
Opened 2021-01-13 08:45 UTC by ValikVityaz

2021-02-18 18:31 UTC, MikhailSadovsky requested changes

2021-02-18 18:31 UTC, MikhailSadovsky commented on sources/plugins/scg/scs/scgfileloader.cpp
> +    /////////////////////////////////////////////
Please remove such lines

2021-02-18 18:31 UTC, MikhailSadovsky commented on sources/plugins/scg/scs/scgfilewriter.cpp
> +    foreach (item, items) {
```suggestion
    foreach (item, items) 
    {
```
Please correct codestyle in all files to be consistent

2021-02-18 18:31 UTC, MikhailSadovsky commented on sources/plugins/scg/scs/scgfileloader.cpp
> +    QString errorStr;
unused variable

2021-03-16 09:14 UTC, MikhailSadovsky approved these changes

2021-03-16 13:18 UTC, deniskoronchik requested changes
More detailed review after some questions solving

2021-03-16 13:18 UTC, deniskoronchik commented on sources/plugins/scg/scg.pro
> +SC_MEMORY_PATH = "../../../thirdparty/sc-machine/sc-memory"
Would be better to compile SCs as separate library instead of a part of SCg one

2021-03-16 13:18 UTC, deniskoronchik commented on sources/plugins/scg/scgwindow.cpp
> +    if (fileName.endsWith(".scs"))
Do map `{"ext", Factory}` ?

2021-03-16 13:18 UTC, deniskoronchik commented on sources/plugins/scg/scgwindow.cpp
> +    res.append("scs");
Get keys from map

2021-03-16 13:18 UTC, deniskoronchik commented on sources/plugins/scg/scs/scgconsts.cpp
> +const QString SCgConsts::CONCEPT_SCG_BUS = "concept_scg_bus";
Let do no use this. Bus is just a visual element.

2021-03-16 13:18 UTC, deniskoronchik commented on sources/plugins/scg/scs/scgfileloader.cpp
> +    QString layoutFileName = file_name.replace(file_name.size() - 3, 3, "layout.scs");
Maybe better to save layout in more suitable format than scs?

2021-03-16 13:18 UTC, deniskoronchik commented on sources/plugins/scg/scs/scgfilewriter.cpp
> +    foreach (item, items)
```suggestion
    for (auto const * item : items)
```

2021-03-16 13:18 UTC, deniskoronchik commented on sources/plugins/scg/scs/scgobjectinforeader.cpp
> +                                                        mIsOwner(isOwner)
layout

2021-03-16 13:18 UTC, deniskoronchik commented on sources/plugins/scg/scs/scgobjectinforeader.cpp
> +    if (mIsOwner)
Why we need this flag?

2021-03-16 13:18 UTC, deniskoronchik commented on sources/plugins/scg/scs/scgobjectinforeader.cpp
> +    else {
```suggestion
    else
    {
```

2021-03-16 13:18 UTC, deniskoronchik commented on sources/plugins/scg/scs/scgobjectinforeader.cpp
> +        nodeInfo->contentMimeTypeRef() = values[SCgConsts::NREL_CONTENT_MIME_TYPE].replace('_','/');
This is very strange solution

2021-03-16 13:18 UTC, deniskoronchik commented on sources/plugins/scg/scs/scgobjectinforeader.cpp
> +        else {
```suggestion
        else
        {
```

2021-03-16 13:18 UTC, deniskoronchik commented on sources/plugins/scg/scs/scgobjectinforeader.cpp
> +    static const QMap<ScType, QString> myTypes =
Move out of method as constant in file.

2021-03-16 13:18 UTC, deniskoronchik commented on sources/plugins/scg/scs/scgstreamwriter.cpp
> +    static const QHash<QString, QString> types =
Same

2021-07-15 16:19 UTC, closed without merging