Fix node type & name inconsistency
ostis-dev/kbe pull request #432
Opened 2021-02-09 16:01 UTC by ValikVityaz

2021-02-17 18:39 UTC, MikhailSadovsky requested changes

2021-02-17 18:39 UTC, MikhailSadovsky commented on sources/plugins/scg/scgscene.cpp
> +            if (idtf.length() != 0)
This check was in line 362

2021-02-17 18:39 UTC, MikhailSadovsky commented on sources/plugins/scg/scgscene.cpp
> +        if (!oldIdtf.isEmpty())
This check was in line 430

2021-02-17 18:39 UTC, MikhailSadovsky commented on sources/plugins/scg/scgscene.cpp
> +    if (isInitial && !oldIdtf.isEmpty()) {
```suggestion
    if (isInitial && !oldIdtf.isEmpty()) 
    {
```

2021-02-17 18:39 UTC, MikhailSadovsky commented on sources/plugins/scg/scgscene.cpp
> +                while (oldIdtf[i] == '_') ++i;
Could you give an example why we need this cycle?

2021-02-17 18:39 UTC, MikhailSadovsky commented
Please specify the issue this change refers to

2021-02-18 00:07 UTC, ValikVityaz commented on sources/plugins/scg/scgscene.cpp
> +                while (oldIdtf[i] == '_') ++i;
If for some reason the name of the node begins with multiple underscores (e.g. ___a)

2021-02-18 09:51 UTC, MikhailSadovsky approved these changes

2021-02-21 17:49 UTC, Zioba approved these changes

2021-02-23 17:06 UTC, deniskoronchik commented
What is an issue that is fixed by this PR?

2021-02-23 23:01 UTC, deniskoronchik commented
As mentioned in the [issue](https://github.com/ostis-dev/kbe/issues/433) problem appears during translation into scs.

Possible solutions:
1. Do checks during scs converting.
Pros:
- solves directly mentioned problem

2. Automatically change types
Cons:
- doesn't allow to do something that is not allowed in memory. But sometimes we need to do that. For example to show restricted constructions with SCg. This is a part of documentation or sometimes we need to show invalid state of KB.

3. Save identifiers with `.x => nrel_system_identifier: [];;`

4. Do nothing. Just add type specifications into scs directly and check scs sources during KB building process.
```
_x => ......;;
_x <- sc_const;;
```

2021-02-23 23:07 UTC, deniskoronchik requested changes
4 possible solutions

2021-03-11 09:11 UTC, ValikVityaz commented
Discussed solution is implemented in #431

2021-03-11 09:11 UTC, closed without merging